export * from './types';
export { allocate, resolveInput } from './allocate';
export { ASSET_CLASSES, BUCKET_LABELS, BUCKET_ORDER, examplesFor } from './catalog';
export * from './profiles';
export { DEMO_SIGNALS, SIGNAL_DIMENSIONS, StaticSignalProvider, netTilts } from './signals';
export type { NetTilts, SignalProvider } from './signals';
export { portfolioRisk } from './risk';
export { formatPlanText } from './format';
export { money, pct } from './util';
export { MAX_RISK_SCORE, RISK_QUESTIONS, SCORE_BANDS, assessRisk, isComplete } from './questionnaire';
export type { Answers, Question, QuestionId, QuestionOption, RiskAssessment } from './questionnaire';
export { ASSET_CLASS_SOURCES, RULE_REFERENCES, SOURCES, ruleReference, sourcesFor } from './sources';
export type { RuleReference, Source } from './sources';
